[2.6 patch] blackfin: let PCI depend on BROKEN
AFAIR there exists blackfin hardware with PCI support, but the support 
currently in the kernel fails to build starting with:

<--  snip  -->

...
  CC      drivers/pci/probe.o
probe.c: In function 'pci_scan_slot':
probe.c:1056: error: implicit declaration of function 'pcibios_scan_all_fns'
make[3]: *** [drivers/pci/probe.o] Error 1

<--  snip  -->

Signed-off-by: Adrian Bunk <bunk@kernel.org>
Signed-off-by: Bryan Wu <cooloney@kernel.org>



git-svn-id: svn://localhost/svn/linux-kernel/trunk@5203 526b6c2d-f592-4532-a319-5dd88ccb003d