[!no_src_qa!] [#3631] Move the CONFIG_KGDB into one block, for easier reading
no_src_qa since bug in checkpatch.pl:
ERROR: no space before that close parenthesis ')'
#12: FILE: arch/blackfin/kernel/traps.c:46:
+               CHK_DEBUGGER(trapnr, sig, info.si_code, fp, ); \

ERROR: need space after that ',' (ctx:VxB)
#12: FILE: arch/blackfin/kernel/traps.c:46:
+               CHK_DEBUGGER(trapnr, sig, info.si_code, fp,); \
                                                          ^


git-svn-id: svn://localhost/svn/linux-kernel/trunk@3761 526b6c2d-f592-4532-a319-5dd88ccb003d